"""drop product_id

Revision ID: 6b5021d001e9
Revises: fb6476a8f474
Create Date: 2024-09-12 18:55:20.511056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5021d001e9'
down_revision: Union[str, None] = 'fb6476a8f474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
