"""product in orders

Revision ID: e4988fcaebaf
Revises: eb98bb3172f5
Create Date: 2024-09-18 14:38:42.262832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4988fcaebaf'
down_revision: Union[str, None] = 'eb98bb3172f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###
